version: "3"
services:
  nginx:
    build: ./services/nginx
    container_name: dt5_nginx
    depends_on: 
      - php
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${APPLICATION}:/var/www/html:rw
      - ${LOG_PATH}:/var/log/nginx:rw
      - ${NGINX_VHOST_PATH}:/etc/nginx/conf.d/:ro
      - ${NGINX_CONFIG_FILENAME}:/etc/nginx/nginx.conf:ro

  php:
    build: ./services/php
    container_name: dt5_php
    expose:
      - "9000"
    links:
      - mysql
    volumes:
      - ${APPLICATION}:/var/www/html:rw
      - ${LOG_PATH}:/var/log:rw
      - ${PHP_INI_PATH}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_PATH}:/usr/local/etc/php-fpm.d/www.conf:rw

  mysql:
    build: ./services/mysql
    container_name: dt5_mysql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql/:rw
      - ${MYSQL_CONFIG_FILENAME}:/etc/mysql/conf.d/mysql.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  redis:
    build: ./services/redis
    container_name: dt5_redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_CONFIG_FILENAME}:/usr/local/etc/redis/redis.conf
      
  composer:
    build: ./services/composer
    container_name: dt5_composer
    depends_on: 
      - mysql
      - redis
      - php
      - nginx
    volumes:
      - ${APPLICATION}:/home/www-data:rw
        
      